#ifndef CNC_HAL_OVERRIDES_H
#define CNC_HAL_OVERRIDES_H
#ifdef __cplusplus
extern "C"
{
#endif

#include "cnc_hal_reset.h"
#define DISABLE_ALL_CONTROLS
#define LIMIT_X_PULLUP_ENABLE
#define LIMIT_Y_PULLUP_ENABLE
#define LIMIT_Z_PULLUP_ENABLE
#define LIMIT_A_PULLUP_ENABLE
#define LIMIT_B_PULLUP_ENABLE
#define LIMIT_C_PULLUP_ENABLE
#define DISABLE_PROBE
#define TOOL1 pen_servo
#define PEN_SERVO_PWM PWM0
#define PEN_SERVO_PWM_DIR DOUT0
#define SOFT_SPI_CLK DOUT30
#define SOFT_SPI_SDO DOUT29
#define SOFT_SPI_SDI DIN29
#define IC74HC595_COUNT 0
#define ENCODERS 0

#define HOMING_CYCLE_0_AXIS_MASK         AXIS_X_HOMING_MASK
#define HOMING_CYCLE_0_ERROR             KINEMATIC_HOMING_ERROR_X
#define HOMING_CYCLE_0_LIMIT_MASK        LINACT0_LIMIT_MASK

#define HOMING_CYCLE_1_AXIS_MASK         AXIS_Y_HOMING_MASK
#define HOMING_CYCLE_1_ERROR             KINEMATIC_HOMING_ERROR_Y
#define HOMING_CYCLE_1_LIMIT_MASK        LINACT1_LIMIT_MASK

#define HOMING_CYCLE_2_AXIS_MASK         AXIS_Z_HOMING_MASK
#define HOMING_CYCLE_2_ERROR             KINEMATIC_HOMING_ERROR_Z
#define HOMING_CYCLE_2_LIMIT_MASK        LINACT2_LIMIT_MASK

#define HOMING_CYCLE_3_AXIS_MASK         0
#define HOMING_CYCLE_3_ERROR             /*not-used*/
#define HOMING_CYCLE_3_LIMIT_MASK        /*not-used*/

#define HOMING_CYCLE_4_AXIS_MASK         AXIS_A_HOMING_MASK
#define HOMING_CYCLE_4_ERROR             KINEMATIC_HOMING_ERROR_A
#define HOMING_CYCLE_4_LIMIT_MASK        LINACT3_LIMIT_MASK

#define HOMING_CYCLE_5_AXIS_MASK         AXIS_B_HOMING_MASK
#define HOMING_CYCLE_5_ERROR             KINEMATIC_HOMING_ERROR_B
#define HOMING_CYCLE_5_LIMIT_MASK        LINACT4_LIMIT_MASK

#define HOMING_CYCLE_6_AXIS_MASK         AXIS_C_HOMING_MASK
#define HOMING_CYCLE_6_ERROR             KINEMATIC_HOMING_ERROR_C
#define HOMING_CYCLE_6_LIMIT_MASK        LINACT5_LIMIT_MASK

#ifdef __cplusplus
}
#endif
#endif
